# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Upload Humansis Demo build to Firebase"
        lane :uploadDemo do
            gradle(task: "clean")
            build_android_app(
                task: "assemble",
                flavor: "demo",
                build_type: "debug"
            )

            firebase_app_distribution(
                app: "1:180061719576:android:87b6cba2ef928618cd876d",
                groups: "applifting",
                release_notes_file: "./release-notes.md"
            )

  end
end
